import mongoose from "mongoose";
import dotenv from "dotenv";
import MenuItem from "./models/MenuItem.js";

dotenv.config();

const menuData = [

  // ============================================
  // STARTERS (12 items)
  // ============================================
  {
    name: "Chicken Tikka",
    description: "Tender chicken marinated in spices, grilled in tandoor. Smoky and juicy.",
    category: "starters",
    price: 550,
    ingredients: ["chicken", "yogurt", "ginger", "garlic", "red chili", "lemon", "cumin"],
    allergens: ["dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 280,
    nutrition: { protein: 32, carbs: 4, fat: 14, fiber: 1, sugar: 2, sodium: 420 },
    healthTags: ["high-protein", "low-carb", "grilled"],
    notRecommendedFor: ["kidney disease"],
    recommendedFor: ["weight loss", "muscle building", "diabetes"],
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600",
    isPopular: true,
    rating: 4.8,
    preparationTime: 25,
    availableFor: ["both"],
  },
  {
    name: "Seekh Kebab",
    description: "Minced beef mixed with herbs and spices, skewered and grilled.",
    category: "starters",
    price: 480,
    ingredients: ["minced beef", "onion", "green chili", "coriander", "garam masala", "ginger"],
    allergens: [],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 310,
    nutrition: { protein: 28, carbs: 3, fat: 20, fiber: 1, sugar: 1, sodium: 380 },
    healthTags: ["high-protein", "grilled", "low-carb"],
    notRecommendedFor: ["heart disease", "obesity"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1529551739587-e242c564f727?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Paneer Tikka",
    description: "Cottage cheese cubes marinated in spiced yogurt, grilled to perfection.",
    category: "starters",
    price: 420,
    ingredients: ["paneer", "yogurt", "bell pepper", "onion", "tomato", "spices"],
    allergens: ["dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 240,
    nutrition: { protein: 18, carbs: 8, fat: 16, fiber: 2, sugar: 3, sodium: 300 },
    healthTags: ["vegetarian", "high-protein", "grilled"],
    notRecommendedFor: ["lactose intolerance"],
    recommendedFor: ["vegetarian", "weight loss"],
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Spring Rolls",
    description: "Crispy rolls stuffed with vegetables and glass noodles.",
    category: "starters",
    price: 320,
    ingredients: ["cabbage", "carrot", "glass noodles", "spring onion", "soy sauce", "flour wrap"],
    allergens: ["gluten", "soy"],
    isVegetarian: true,
    isVegan: true,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 190,
    nutrition: { protein: 4, carbs: 28, fat: 8, fiber: 3, sugar: 5, sodium: 280 },
    healthTags: ["vegetarian", "low-calorie"],
    notRecommendedFor: ["celiac disease"],
    recommendedFor: ["vegetarian"],
    image: "https://images.unsplash.com/photo-1606525437110-43c2c72e0bf3?w=600",
    isPopular: false,
    rating: 4.3,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Chicken Wings",
    description: "Crispy fried chicken wings tossed in spicy buffalo sauce.",
    category: "starters",
    price: 580,
    ingredients: ["chicken wings", "flour", "buffalo sauce", "butter", "garlic"],
    allergens: ["gluten", "dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 420,
    nutrition: { protein: 28, carbs: 18, fat: 28, fiber: 1, sugar: 4, sodium: 680 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["obesity", "heart disease", "hypertension"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600",
    isPopular: true,
    rating: 4.6,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Fish Fingers",
    description: "Crispy battered fish strips served with tartar sauce.",
    category: "starters",
    price: 520,
    ingredients: ["fish fillet", "flour", "breadcrumbs", "egg", "spices"],
    allergens: ["gluten", "eggs", "fish"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 350,
    nutrition: { protein: 22, carbs: 28, fat: 16, fiber: 1, sugar: 2, sodium: 480 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["fish allergy"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1618593346874-29bf5d2e8358?w=600",
    isPopular: false,
    rating: 4.4,
    preparationTime: 18,
    availableFor: ["both"],
  },
  {
    name: "Garlic Bread",
    description: "Toasted bread with garlic butter and herbs.",
    category: "starters",
    price: 180,
    ingredients: ["bread", "butter", "garlic", "parsley"],
    allergens: ["gluten", "dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 220,
    nutrition: { protein: 5, carbs: 28, fat: 10, fiber: 1, sugar: 2, sodium: 320 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["celiac disease"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=600",
    isPopular: true,
    rating: 4.5,
    preparationTime: 8,
    availableFor: ["both"],
  },
  {
    name: "Mozzarella Sticks",
    description: "Crispy fried mozzarella cheese sticks with marinara sauce.",
    category: "starters",
    price: 420,
    ingredients: ["mozzarella", "flour", "breadcrumbs", "egg", "marinara"],
    allergens: ["gluten", "dairy", "eggs"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 380,
    nutrition: { protein: 18, carbs: 28, fat: 22, fiber: 1, sugar: 4, sodium: 580 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["celiac disease", "lactose intolerance"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600",
    isPopular: false,
    rating: 4.3,
    preparationTime: 12,
    availableFor: ["both"],
  },
  {
    name: "Onion Rings",
    description: "Crispy battered onion rings served with dip.",
    category: "starters",
    price: 250,
    ingredients: ["onion", "flour", "buttermilk", "breadcrumbs", "spices"],
    allergens: ["gluten", "dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 340,
    nutrition: { protein: 4, carbs: 42, fat: 18, fiber: 2, sugar: 6, sodium: 420 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["celiac disease"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1639024471283-03518883512d?w=600",
    isPopular: true,
    rating: 4.5,
    preparationTime: 12,
    availableFor: ["both"],
  },
  {
    name: "Samosa",
    description: "Crispy pastry filled with spiced potatoes and peas.",
    category: "starters",
    price: 180,
    ingredients: ["flour", "potato", "peas", "spices", "oil"],
    allergens: ["gluten"],
    isVegetarian: true,
    isVegan: true,
    isSpicy: true,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 280,
    nutrition: { protein: 5, carbs: 38, fat: 12, fiber: 3, sugar: 2, sodium: 380 },
    healthTags: ["vegetarian", "traditional"],
    notRecommendedFor: ["celiac disease", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Chicken Corn Soup",
    description: "Sweet corn soup with shredded chicken and egg drops.",
    category: "starters",
    price: 220,
    ingredients: ["chicken", "corn", "egg", "cornflour", "soy sauce"],
    allergens: ["eggs", "soy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 180,
    nutrition: { protein: 12, carbs: 22, fat: 6, fiber: 2, sugar: 4, sodium: 520 },
    healthTags: ["low-calorie"],
    notRecommendedFor: ["hypertension"],
    recommendedFor: ["weight loss", "diabetes"],
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600",
    isPopular: false,
    rating: 4.3,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Stuffed Mushrooms",
    description: "Mushrooms caps stuffed with cream cheese and herbs.",
    category: "starters",
    price: 450,
    ingredients: ["mushroom", "cream cheese", "garlic", "parsley", "breadcrumbs"],
    allergens: ["gluten", "dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 260,
    nutrition: { protein: 8, carbs: 14, fat: 18, fiber: 2, sugar: 3, sodium: 280 },
    healthTags: ["vegetarian", "low-carb"],
    notRecommendedFor: ["celiac disease", "lactose intolerance"],
    recommendedFor: ["vegetarian"],
    image: "https://images.unsplash.com/photo-1529001092324-457f4de8f1a9?w=600",
    isPopular: false,
    rating: 4.4,
    preparationTime: 20,
    availableFor: ["both"],
  },

  // ============================================
  // DESI FOOD (15 items)
  // ============================================
  {
    name: "Chicken Biryani",
    description: "Fragrant basmati rice layered with spiced chicken and saffron.",
    category: "desifood",
    price: 420,
    ingredients: ["basmati rice", "chicken", "onion", "tomato", "saffron", "yogurt", "spices"],
    allergens: ["dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 520,
    nutrition: { protein: 28, carbs: 58, fat: 18, fiber: 2, sugar: 4, sodium: 680 },
    healthTags: ["high-protein", "traditional"],
    notRecommendedFor: ["diabetes", "obesity", "hypertension"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1563379091339-03246963d56e?w=600",
    isPopular: true,
    rating: 4.9,
    preparationTime: 45,
    availableFor: ["both"],
  },
  {
    name: "Mutton Karahi",
    description: "Tender mutton cooked in a wok with tomatoes and aromatic spices.",
    category: "desifood",
    price: 1200,
    ingredients: ["mutton", "tomato", "ginger", "garlic", "green chili", "coriander", "oil"],
    allergens: [],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 480,
    nutrition: { protein: 35, carbs: 6, fat: 34, fiber: 2, sugar: 4, sodium: 520 },
    healthTags: ["high-protein", "low-carb", "traditional"],
    notRecommendedFor: ["heart disease", "obesity", "hypertension"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600",
    isPopular: true,
    rating: 4.8,
    preparationTime: 50,
    availableFor: ["both"],
  },
  {
    name: "Chicken Karahi",
    description: "Juicy chicken pieces cooked in spiced tomato gravy.",
    category: "desifood",
    price: 680,
    ingredients: ["chicken", "tomato", "ginger", "garlic", "green chili", "coriander", "spices"],
    allergens: [],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 380,
    nutrition: { protein: 30, carbs: 8, fat: 24, fiber: 2, sugar: 4, sodium: 480 },
    healthTags: ["high-protein", "low-carb", "traditional"],
    notRecommendedFor: ["heart disease", "hypertension"],
    recommendedFor: ["muscle building", "diabetes"],
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600",
    isPopular: true,
    rating: 4.8,
    preparationTime: 35,
    availableFor: ["both"],
  },
  {
    name: "Dal Makhani",
    description: "Slow-cooked black lentils with butter, cream and aromatic spices.",
    category: "desifood",
    price: 380,
    ingredients: ["black lentils", "kidney beans", "butter", "cream", "tomato", "onion", "spices"],
    allergens: ["dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 350,
    nutrition: { protein: 14, carbs: 42, fat: 14, fiber: 12, sugar: 5, sodium: 380 },
    healthTags: ["vegetarian", "high-fiber", "heart-healthy"],
    notRecommendedFor: ["kidney disease", "lactose intolerance"],
    recommendedFor: ["diabetes", "heart health", "weight loss"],
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600",
    isPopular: false,
    rating: 4.6,
    preparationTime: 30,
    availableFor: ["both"],
  },
  {
    name: "Palak Paneer",
    description: "Fresh spinach puree with soft cottage cheese cubes in mild gravy.",
    category: "desifood",
    price: 400,
    ingredients: ["spinach", "paneer", "onion", "tomato", "ginger", "garlic", "cream", "spices"],
    allergens: ["dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 290,
    nutrition: { protein: 16, carbs: 12, fat: 20, fiber: 4, sugar: 3, sodium: 340 },
    healthTags: ["vegetarian", "iron-rich", "calcium-rich", "heart-healthy"],
    notRecommendedFor: ["kidney disease", "lactose intolerance"],
    recommendedFor: ["anemia", "weight loss", "diabetes"],
    image: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 25,
    availableFor: ["both"],
  },
  {
    name: "Nihari",
    description: "Slow-cooked beef shank in a rich spiced gravy.",
    category: "desifood",
    price: 550,
    ingredients: ["beef shank", "bone marrow", "ginger", "onion", "nihari spices", "wheat flour", "ghee"],
    allergens: ["gluten", "dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 580,
    nutrition: { protein: 38, carbs: 18, fat: 38, fiber: 2, sugar: 2, sodium: 780 },
    healthTags: ["high-protein", "traditional"],
    notRecommendedFor: ["heart disease", "hypertension", "obesity", "diabetes"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 60,
    availableFor: ["both"],
  },
  {
    name: "Aloo Gobi",
    description: "Potato and cauliflower stir-fried with cumin and turmeric.",
    category: "desifood",
    price: 280,
    ingredients: ["potato", "cauliflower", "cumin", "turmeric", "onion", "tomato", "coriander"],
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 210,
    nutrition: { protein: 5, carbs: 32, fat: 8, fiber: 6, sugar: 5, sodium: 280 },
    healthTags: ["vegetarian", "vegan", "low-calorie", "heart-healthy"],
    notRecommendedFor: ["diabetes"],
    recommendedFor: ["weight loss", "heart health", "anemia"],
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600",
    isPopular: false,
    rating: 4.2,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Haleem",
    description: "Slow-cooked blend of wheat, barley, lentils and meat with spices.",
    category: "desifood",
    price: 480,
    ingredients: ["wheat", "barley", "lentils", "beef", "ginger", "garlic", "spices"],
    allergens: ["gluten"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 450,
    nutrition: { protein: 28, carbs: 48, fat: 16, fiber: 8, sugar: 4, sodium: 520 },
    healthTags: ["high-protein", "high-fiber", "traditional"],
    notRecommendedFor: ["celiac disease", "obesity"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1533609914594-d1c72d9b9cad?w=600",
    isPopular: true,
    rating: 4.8,
    preparationTime: 45,
    availableFor: ["both"],
  },
  {
    name: "Butter Chicken",
    description: "Tender chicken in creamy tomato butter gravy.",
    category: "desifood",
    price: 650,
    ingredients: ["chicken", "butter", "cream", "tomato", "cashew", "spices"],
    allergens: ["dairy", "nuts"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 480,
    nutrition: { protein: 32, carbs: 12, fat: 32, fiber: 2, sugar: 6, sodium: 580 },
    healthTags: ["high-protein", "traditional"],
    notRecommendedFor: ["heart disease", "obesity", "lactose intolerance"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600",
    isPopular: true,
    rating: 4.9,
    preparationTime: 40,
    availableFor: ["both"],
  },
  {
    name: "Chapli Kebab",
    description: "Spicy flattened beef kebab with pomegranate and coriander.",
    category: "desifood",
    price: 350,
    ingredients: ["beef mince", "pomegranate", "coriander", "green chili", "onion", "tomato"],
    allergens: [],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 320,
    nutrition: { protein: 24, carbs: 8, fat: 22, fiber: 2, sugar: 3, sodium: 420 },
    healthTags: ["high-protein", "low-carb", "grilled"],
    notRecommendedFor: ["heart disease", "hypertension"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1593195585361-2af590061e36?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 25,
    availableFor: ["both"],
  },
  {
    name: "Malai Boti",
    description: "Creamy chicken skewers marinated with cream and mild spices.",
    category: "desifood",
    price: 520,
    ingredients: ["chicken", "cream", "cheese", "ginger", "garlic", "green chili"],
    allergens: ["dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 380,
    nutrition: { protein: 34, carbs: 6, fat: 24, fiber: 0, sugar: 3, sodium: 480 },
    healthTags: ["high-protein", "low-carb"],
    notRecommendedFor: ["lactose intolerance", "obesity"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 30,
    availableFor: ["both"],
  },
  {
    name: "Shahi Paneer",
    description: "Cottage cheese in rich creamy cashew gravy.",
    category: "desifood",
    price: 450,
    ingredients: ["paneer", "cashew", "cream", "onion", "tomato", "spices"],
    allergens: ["dairy", "nuts"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 410,
    nutrition: { protein: 18, carbs: 16, fat: 28, fiber: 3, sugar: 6, sodium: 380 },
    healthTags: ["vegetarian", "high-protein"],
    notRecommendedFor: ["lactose intolerance", "obesity"],
    recommendedFor: ["vegetarian"],
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600",
    isPopular: false,
    rating: 4.6,
    preparationTime: 30,
    availableFor: ["both"],
  },
  {
    name: "Sindhi Biryani",
    description: "Spicy biryani with potatoes, chicken and plum.",
    category: "desifood",
    price: 450,
    ingredients: ["basmati rice", "chicken", "potato", "plum", "yogurt", "spices"],
    allergens: ["dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 540,
    nutrition: { protein: 30, carbs: 62, fat: 20, fiber: 3, sugar: 5, sodium: 720 },
    healthTags: ["high-protein", "traditional"],
    notRecommendedFor: ["diabetes", "obesity", "hypertension"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600",
    isPopular: false,
    rating: 4.6,
    preparationTime: 50,
    availableFor: ["both"],
  },
  {
    name: "Kadhi Pakora",
    description: "Yogurt-based curry with fried gram flour dumplings.",
    category: "desifood",
    price: 320,
    ingredients: ["yogurt", "gram flour", "onion", "spices", "pakoras"],
    allergens: ["dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 290,
    nutrition: { protein: 10, carbs: 36, fat: 12, fiber: 4, sugar: 8, sodium: 480 },
    healthTags: ["vegetarian", "traditional"],
    notRecommendedFor: ["lactose intolerance", "obesity"],
    recommendedFor: ["vegetarian"],
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600",
    isPopular: false,
    rating: 4.4,
    preparationTime: 35,
    availableFor: ["both"],
  },
  {
    name: "Bihari Kebab",
    description: "Tender beef marinated with papaya and spices, grilled.",
    category: "desifood",
    price: 480,
    ingredients: ["beef", "papaya", "yogurt", "ginger", "garlic", "spices"],
    allergens: ["dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 360,
    nutrition: { protein: 32, carbs: 4, fat: 22, fiber: 1, sugar: 2, sodium: 440 },
    healthTags: ["high-protein", "low-carb", "grilled"],
    notRecommendedFor: ["heart disease", "hypertension"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 30,
    availableFor: ["both"],
  },

  // ============================================
  // CHINESE (12 items)
  // ============================================
  {
    name: "Chicken Chow Mein",
    description: "Stir-fried noodles with chicken and vegetables in soy sauce.",
    category: "chinese",
    price: 480,
    ingredients: ["egg noodles", "chicken", "cabbage", "carrot", "spring onion", "soy sauce"],
    allergens: ["gluten", "soy", "eggs"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 420,
    nutrition: { protein: 22, carbs: 52, fat: 12, fiber: 3, sugar: 6, sodium: 860 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["celiac disease", "hypertension"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600",
    isPopular: true,
    rating: 4.6,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Kung Pao Chicken",
    description: "Spicy stir-fried chicken with peanuts and dried chilies.",
    category: "chinese",
    price: 520,
    ingredients: ["chicken", "peanuts", "dried chili", "zucchini", "bell pepper", "soy sauce"],
    allergens: ["nuts", "soy", "gluten"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 460,
    nutrition: { protein: 30, carbs: 22, fat: 28, fiber: 3, sugar: 8, sodium: 780 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["hypertension", "heart disease", "nut allergy"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Egg Fried Rice",
    description: "Wok-tossed rice with egg and vegetables.",
    category: "chinese",
    price: 380,
    ingredients: ["rice", "egg", "carrot", "peas", "spring onion", "soy sauce"],
    allergens: ["eggs", "soy", "gluten"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 390,
    nutrition: { protein: 10, carbs: 62, fat: 12, fiber: 2, sugar: 4, sodium: 680 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["diabetes", "hypertension"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600",
    isPopular: true,
    rating: 4.5,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Hot and Sour Soup",
    description: "Tangy soup with tofu, mushrooms and bamboo shoots.",
    category: "chinese",
    price: 280,
    ingredients: ["tofu", "mushrooms", "bamboo shoots", "egg", "vinegar", "soy sauce"],
    allergens: ["eggs", "soy", "gluten"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 150,
    nutrition: { protein: 8, carbs: 18, fat: 4, fiber: 2, sugar: 3, sodium: 720 },
    healthTags: ["vegetarian", "low-calorie"],
    notRecommendedFor: ["hypertension", "kidney disease"],
    recommendedFor: ["weight loss", "diabetes"],
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600",
    isPopular: false,
    rating: 4.3,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Chicken Manchurian",
    description: "Crispy chicken balls in tangy Manchurian sauce.",
    category: "chinese",
    price: 420,
    ingredients: ["chicken", "soy sauce", "garlic", "ginger", "spring onion", "cornflour"],
    allergens: ["gluten", "soy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 360,
    nutrition: { protein: 20, carbs: 32, fat: 16, fiber: 2, sugar: 8, sodium: 820 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["hypertension", "celiac disease"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600",
    isPopular: true,
    rating: 4.5,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Schezwan Fried Rice",
    description: "Spicy Schezwan style fried rice with vegetables.",
    category: "chinese",
    price: 420,
    ingredients: ["rice", "schezwan sauce", "vegetables", "spring onion", "soy sauce"],
    allergens: ["gluten", "soy"],
    isVegetarian: true,
    isVegan: true,
    isSpicy: true,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 410,
    nutrition: { protein: 8, carbs: 68, fat: 14, fiber: 3, sugar: 6, sodium: 780 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["hypertension", "celiac disease"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600",
    isPopular: false,
    rating: 4.4,
    preparationTime: 18,
    availableFor: ["both"],
  },
  {
    name: "Spring Onion Chicken",
    description: "Stir-fried chicken with spring onions in light sauce.",
    category: "chinese",
    price: 480,
    ingredients: ["chicken", "spring onion", "ginger", "garlic", "soy sauce", "oyster sauce"],
    allergens: ["gluten", "soy", "shellfish"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 340,
    nutrition: { protein: 34, carbs: 12, fat: 16, fiber: 2, sugar: 4, sodium: 680 },
    healthTags: ["high-protein", "low-carb"],
    notRecommendedFor: ["hypertension"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1617098900591-3d909b9f9a5a?w=600",
    isPopular: false,
    rating: 4.3,
    preparationTime: 18,
    availableFor: ["both"],
  },
  {
    name: "Honey Glazed Chicken",
    description: "Sweet and sticky honey glazed crispy chicken.",
    category: "chinese",
    price: 520,
    ingredients: ["chicken", "honey", "soy sauce", "ginger", "garlic", "sesame"],
    allergens: ["gluten", "soy", "sesame"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 440,
    nutrition: { protein: 26, carbs: 42, fat: 18, fiber: 1, sugar: 28, sodium: 520 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["diabetes", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Vegetable Spring Rolls",
    description: "Crispy rolls with mixed vegetables and glass noodles.",
    category: "chinese",
    price: 320,
    ingredients: ["cabbage", "carrot", "glass noodles", "spring onion", "soy sauce"],
    allergens: ["gluten", "soy"],
    isVegetarian: true,
    isVegan: true,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 190,
    nutrition: { protein: 4, carbs: 28, fat: 8, fiber: 2, sugar: 4, sodium: 480 },
    healthTags: ["vegetarian", "low-calorie"],
    notRecommendedFor: ["celiac disease"],
    recommendedFor: ["vegetarian", "weight loss"],
    image: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=600",
    isPopular: false,
    rating: 4.3,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Chilli Garlic Noodles",
    description: "Spicy noodles with garlic and chili sauce.",
    category: "chinese",
    price: 450,
    ingredients: ["noodles", "garlic", "red chili", "soy sauce", "spring onion", "bell pepper"],
    allergens: ["gluten", "soy"],
    isVegetarian: true,
    isVegan: true,
    isSpicy: true,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 430,
    nutrition: { protein: 10, carbs: 68, fat: 14, fiber: 3, sugar: 5, sodium: 720 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["celiac disease", "hypertension"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600",
    isPopular: false,
    rating: 4.4,
    preparationTime: 18,
    availableFor: ["both"],
  },
  {
    name: "Sweet and Sour Chicken",
    description: "Crispy chicken with sweet and tangy sauce, bell peppers and pineapple.",
    category: "chinese",
    price: 520,
    ingredients: ["chicken", "bell pepper", "pineapple", "sweet and sour sauce", "onion"],
    allergens: ["gluten", "soy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 460,
    nutrition: { protein: 24, carbs: 48, fat: 18, fiber: 2, sugar: 32, sodium: 580 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["diabetes", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600",
    isPopular: true,
    rating: 4.5,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Dumplings",
    description: "Steamed or fried dumplings filled with chicken and vegetables.",
    category: "chinese",
    price: 380,
    ingredients: ["flour", "chicken", "cabbage", "ginger", "garlic", "soy sauce"],
    allergens: ["gluten", "soy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 280,
    nutrition: { protein: 14, carbs: 32, fat: 10, fiber: 2, sugar: 3, sodium: 480 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["celiac disease"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=600",
    isPopular: true,
    rating: 4.6,
    preparationTime: 20,
    availableFor: ["both"],
  },

  // ============================================
  // FAST FOOD (12 items)
  // ============================================
  {
    name: "Zinger Burger",
    description: "Crispy spiced chicken fillet in a toasted bun with lettuce and mayo.",
    category: "fastfood",
    price: 650,
    ingredients: ["chicken fillet", "flour bun", "lettuce", "mayonnaise", "pickles"],
    allergens: ["gluten", "dairy", "eggs"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 520,
    nutrition: { protein: 28, carbs: 48, fat: 24, fiber: 2, sugar: 8, sodium: 820 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["obesity", "heart disease", "hypertension", "celiac disease"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Beef Smash Burger",
    description: "Double smashed beef patty with cheddar and caramelized onions.",
    category: "fastfood",
    price: 750,
    ingredients: ["beef patty", "cheddar cheese", "onion", "brioche bun", "special sauce"],
    allergens: ["gluten", "dairy", "eggs"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 680,
    nutrition: { protein: 38, carbs: 42, fat: 38, fiber: 2, sugar: 10, sodium: 920 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["obesity", "heart disease", "hypertension", "diabetes"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1553979459-d2229ba7433a?w=600",
    isPopular: true,
    rating: 4.8,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Crispy Fries",
    description: "Golden crispy fries with signature spice blend.",
    category: "fastfood",
    price: 220,
    ingredients: ["potato", "vegetable oil", "salt", "spice blend"],
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 320,
    nutrition: { protein: 4, carbs: 42, fat: 16, fiber: 3, sugar: 1, sodium: 380 },
    healthTags: ["vegetarian", "vegan"],
    notRecommendedFor: ["obesity", "diabetes", "hypertension"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=600",
    isPopular: true,
    rating: 4.5,
    preparationTime: 10,
    availableFor: ["both"],
  },
  {
    name: "Grilled Chicken Wrap",
    description: "Grilled chicken with fresh veggies and garlic sauce in a tortilla.",
    category: "fastfood",
    price: 480,
    ingredients: ["chicken breast", "tortilla", "lettuce", "tomato", "cucumber", "garlic sauce"],
    allergens: ["gluten", "dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 380,
    nutrition: { protein: 32, carbs: 30, fat: 12, fiber: 3, sugar: 4, sodium: 580 },
    healthTags: ["high-protein", "grilled", "low-fat"],
    notRecommendedFor: ["celiac disease"],
    recommendedFor: ["weight loss", "diabetes", "heart health"],
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600",
    isPopular: false,
    rating: 4.4,
    preparationTime: 12,
    availableFor: ["both"],
  },
  {
    name: "Chicken Nuggets",
    description: "Crispy bite-sized chicken nuggets with dip.",
    category: "fastfood",
    price: 350,
    ingredients: ["chicken", "flour", "breadcrumbs", "spices"],
    allergens: ["gluten", "dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 380,
    nutrition: { protein: 18, carbs: 32, fat: 20, fiber: 1, sugar: 2, sodium: 580 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["obesity", "celiac disease"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1562962230-16e4623d36e6?w=600",
    isPopular: true,
    rating: 4.5,
    preparationTime: 12,
    availableFor: ["both"],
  },
  {
    name: "Cheese Pizza",
    description: "Classic pizza with tomato sauce and triple cheese.",
    category: "fastfood",
    price: 850,
    ingredients: ["pizza dough", "tomato sauce", "mozzarella", "cheddar", "parmesan"],
    allergens: ["gluten", "dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 620,
    nutrition: { protein: 24, carbs: 72, fat: 26, fiber: 3, sugar: 8, sodium: 880 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["celiac disease", "obesity", "diabetes"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Chicken Popcorn",
    description: "Bite-sized crispy fried chicken pieces.",
    category: "fastfood",
    price: 280,
    ingredients: ["chicken breast", "flour", "spices", "oil"],
    allergens: ["gluten"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 340,
    nutrition: { protein: 22, carbs: 26, fat: 16, fiber: 1, sugar: 1, sodium: 520 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["celiac disease"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1592492152545-969a3ea5ea04?w=600",
    isPopular: false,
    rating: 4.4,
    preparationTime: 10,
    availableFor: ["both"],
  },
  {
    name: "Chicken Shawarma",
    description: "Grilled chicken wrapped in pita with garlic sauce and pickles.",
    category: "fastfood",
    price: 520,
    ingredients: ["chicken", "pita bread", "garlic sauce", "pickles", "fries"],
    allergens: ["gluten", "dairy", "eggs"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 480,
    nutrition: { protein: 34, carbs: 42, fat: 20, fiber: 3, sugar: 4, sodium: 780 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["celiac disease"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Chicken Burger",
    description: "Grilled chicken patty with lettuce, tomato and mayo.",
    category: "fastfood",
    price: 550,
    ingredients: ["chicken patty", "flour bun", "lettuce", "tomato", "mayonnaise"],
    allergens: ["gluten", "dairy", "eggs"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 480,
    nutrition: { protein: 32, carbs: 44, fat: 20, fiber: 2, sugar: 6, sodium: 680 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["celiac disease", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Veggie Burger",
    description: "Plant-based patty with fresh vegetables and vegan sauce.",
    category: "fastfood",
    price: 480,
    ingredients: ["plant-based patty", "whole wheat bun", "lettuce", "tomato", "onion", "vegan sauce"],
    allergens: ["gluten"],
    isVegetarian: true,
    isVegan: true,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 420,
    nutrition: { protein: 18, carbs: 52, fat: 14, fiber: 6, sugar: 8, sodium: 620 },
    healthTags: ["vegetarian", "vegan", "high-fiber"],
    notRecommendedFor: ["celiac disease"],
    recommendedFor: ["vegetarian", "vegan", "weight loss"],
    image: "https://images.unsplash.com/photo-1551782450-17144efb9c50?w=600",
    isPopular: false,
    rating: 4.3,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Mozzarella Sticks",
    description: "Crispy cheese sticks with marinara sauce.",
    category: "fastfood",
    price: 400,
    ingredients: ["mozzarella", "flour", "breadcrumbs", "marinara sauce"],
    allergens: ["gluten", "dairy", "eggs"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 380,
    nutrition: { protein: 16, carbs: 32, fat: 20, fiber: 2, sugar: 4, sodium: 680 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["celiac disease", "lactose intolerance"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600",
    isPopular: false,
    rating: 4.4,
    preparationTime: 12,
    availableFor: ["both"],
  },
  {
    name: "Chicken Fingers",
    description: "Crispy chicken strips served with honey mustard.",
    category: "fastfood",
    price: 420,
    ingredients: ["chicken breast", "flour", "breadcrumbs", "spices", "honey mustard"],
    allergens: ["gluten", "eggs", "mustard"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 390,
    nutrition: { protein: 28, carbs: 34, fat: 16, fiber: 1, sugar: 6, sodium: 580 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["celiac disease"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1592492152545-969a3ea5ea04?w=600",
    isPopular: false,
    rating: 4.4,
    preparationTime: 15,
    availableFor: ["both"],
  },

  // ============================================
  // DESSERTS (10 items)
  // ============================================
  {
    name: "Gulab Jamun",
    description: "Soft milk-solid dumplings in rose-flavored sugar syrup.",
    category: "desserts",
    price: 220,
    ingredients: ["milk powder", "flour", "sugar", "rose water", "cardamom", "ghee"],
    allergens: ["dairy", "gluten"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 380,
    nutrition: { protein: 6, carbs: 62, fat: 12, fiber: 0, sugar: 52, sodium: 80 },
    healthTags: ["vegetarian", "traditional"],
    notRecommendedFor: ["diabetes", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1601303516534-bf4e8b666d53?w=600",
    isPopular: true,
    rating: 4.9,
    preparationTime: 10,
    availableFor: ["both"],
  },
  {
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center, served with ice cream.",
    category: "desserts",
    price: 380,
    ingredients: ["dark chocolate", "butter", "eggs", "flour", "sugar", "vanilla"],
    allergens: ["dairy", "gluten", "eggs"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 480,
    nutrition: { protein: 8, carbs: 58, fat: 24, fiber: 3, sugar: 42, sodium: 120 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["diabetes", "obesity", "heart disease"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600",
    isPopular: true,
    rating: 4.8,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Kheer",
    description: "Traditional rice pudding with milk, sugar, cardamom and dry fruits.",
    category: "desserts",
    price: 180,
    ingredients: ["rice", "milk", "sugar", "cardamom", "almonds", "pistachios"],
    allergens: ["dairy", "nuts"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 320,
    nutrition: { protein: 8, carbs: 52, fat: 10, fiber: 1, sugar: 38, sodium: 60 },
    healthTags: ["vegetarian", "traditional"],
    notRecommendedFor: ["diabetes", "obesity", "lactose intolerance"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600",
    isPopular: false,
    rating: 4.6,
    preparationTime: 10,
    availableFor: ["both"],
  },
  {
    name: "Fruit Salad",
    description: "Fresh seasonal fruits with honey-lemon dressing.",
    category: "desserts",
    price: 220,
    ingredients: ["apple", "banana", "grapes", "watermelon", "mango", "honey", "lemon"],
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 160,
    nutrition: { protein: 2, carbs: 38, fat: 1, fiber: 5, sugar: 30, sodium: 20 },
    healthTags: ["vegetarian", "vegan", "low-calorie", "high-fiber"],
    notRecommendedFor: ["diabetes"],
    recommendedFor: ["weight loss", "heart health", "anemia"],
    image: "https://images.unsplash.com/photo-1568158879083-c42860933ed7?w=600",
    isPopular: false,
    rating: 4.4,
    preparationTime: 10,
    availableFor: ["both"],
  },
  {
    name: "Brownie with Ice Cream",
    description: "Warm chocolate brownie with vanilla ice cream and chocolate sauce.",
    category: "desserts",
    price: 350,
    ingredients: ["chocolate brownie", "vanilla ice cream", "chocolate sauce", "nuts"],
    allergens: ["dairy", "gluten", "eggs", "nuts"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 520,
    nutrition: { protein: 8, carbs: 68, fat: 26, fiber: 2, sugar: 48, sodium: 180 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["diabetes", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600",
    isPopular: true,
    rating: 4.8,
    preparationTime: 12,
    availableFor: ["both"],
  },
  {
    name: "Ice Cream Sundae",
    description: "Vanilla ice cream with chocolate sauce, nuts and cherry.",
    category: "desserts",
    price: 280,
    ingredients: ["vanilla ice cream", "chocolate sauce", "nuts", "cherry"],
    allergens: ["dairy", "nuts"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 380,
    nutrition: { protein: 6, carbs: 48, fat: 18, fiber: 1, sugar: 42, sodium: 80 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["diabetes", "obesity", "lactose intolerance"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 8,
    availableFor: ["both"],
  },
  {
    name: "Jalebi",
    description: "Crispy orange spiral sweets soaked in sugar syrup.",
    category: "desserts",
    price: 150,
    ingredients: ["flour", "sugar", "saffron", "cardamom", "ghee"],
    allergens: ["gluten", "dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 280,
    nutrition: { protein: 2, carbs: 52, fat: 8, fiber: 0, sugar: 48, sodium: 40 },
    healthTags: ["vegetarian", "traditional"],
    notRecommendedFor: ["diabetes", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 10,
    availableFor: ["both"],
  },
  {
    name: "Ras Malai",
    description: "Soft cheese patties in creamy sweet milk with cardamom.",
    category: "desserts",
    price: 250,
    ingredients: ["paneer", "milk", "sugar", "cardamom", "saffron", "pistachios"],
    allergens: ["dairy", "nuts"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 310,
    nutrition: { protein: 10, carbs: 42, fat: 12, fiber: 0, sugar: 38, sodium: 120 },
    healthTags: ["vegetarian", "calcium-rich"],
    notRecommendedFor: ["diabetes", "obesity", "lactose intolerance"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600",
    isPopular: false,
    rating: 4.6,
    preparationTime: 10,
    availableFor: ["both"],
  },
  {
    name: "Cheesecake",
    description: "New York style creamy cheesecake with berry compote.",
    category: "desserts",
    price: 420,
    ingredients: ["cream cheese", "sugar", "eggs", "butter", "graham crackers", "berries"],
    allergens: ["dairy", "gluten", "eggs"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 480,
    nutrition: { protein: 8, carbs: 42, fat: 28, fiber: 1, sugar: 32, sodium: 280 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["diabetes", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 10,
    availableFor: ["both"],
  },
  {
    name: "Gajar Ka Halwa",
    description: "Slow-cooked carrot pudding with milk, sugar and nuts.",
    category: "desserts",
    price: 260,
    ingredients: ["carrot", "milk", "sugar", "ghee", "cardamom", "almonds"],
    allergens: ["dairy", "nuts"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 340,
    nutrition: { protein: 6, carbs: 48, fat: 14, fiber: 3, sugar: 38, sodium: 80 },
    healthTags: ["vegetarian", "traditional", "high-fiber"],
    notRecommendedFor: ["diabetes", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 25,
    availableFor: ["both"],
  },

  // ============================================
  // BEVERAGES (10 items)
  // ============================================
  {
    name: "Mango Lassi",
    description: "Thick creamy yogurt drink with fresh Chaunsa mangoes.",
    category: "beverages",
    price: 220,
    ingredients: ["mango", "yogurt", "milk", "sugar", "cardamom"],
    allergens: ["dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 280,
    nutrition: { protein: 6, carbs: 48, fat: 6, fiber: 2, sugar: 42, sodium: 60 },
    healthTags: ["vegetarian", "probiotic"],
    notRecommendedFor: ["diabetes", "obesity", "lactose intolerance"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600",
    isPopular: true,
    rating: 4.8,
    preparationTime: 5,
    availableFor: ["both"],
  },
  {
    name: "Fresh Lime Soda",
    description: "Fresh lime with sparkling water and mint. Refreshing!",
    category: "beverages",
    price: 150,
    ingredients: ["lime", "sparkling water", "mint", "salt", "sugar"],
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 60,
    nutrition: { protein: 0, carbs: 14, fat: 0, fiber: 0, sugar: 12, sodium: 180 },
    healthTags: ["vegetarian", "vegan", "low-calorie"],
    notRecommendedFor: ["hypertension"],
    recommendedFor: ["weight loss", "diabetes"],
    image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=600",
    isPopular: true,
    rating: 4.6,
    preparationTime: 3,
    availableFor: ["both"],
  },
  {
    name: "Green Tea",
    description: "Premium green tea brewed to perfection. Antioxidant rich.",
    category: "beverages",
    price: 120,
    ingredients: ["green tea leaves", "water", "honey", "lemon"],
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 30,
    nutrition: { protein: 0, carbs: 6, fat: 0, fiber: 0, sugar: 4, sodium: 10 },
    healthTags: ["vegetarian", "vegan", "low-calorie", "antioxidant", "heart-healthy"],
    notRecommendedFor: [],
    recommendedFor: ["weight loss", "heart health", "diabetes", "obesity"],
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600",
    isPopular: false,
    rating: 4.4,
    preparationTime: 5,
    availableFor: ["both"],
  },
  {
    name: "Rooh Afza Sharbat",
    description: "Classic Pakistani rose-based drink with milk.",
    category: "beverages",
    price: 130,
    ingredients: ["rooh afza", "milk", "ice", "basil seeds"],
    allergens: ["dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 180,
    nutrition: { protein: 4, carbs: 34, fat: 3, fiber: 0, sugar: 30, sodium: 40 },
    healthTags: ["vegetarian", "traditional"],
    notRecommendedFor: ["diabetes", "lactose intolerance"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 3,
    availableFor: ["both"],
  },
  {
    name: "Chai (Pakistani Tea)",
    description: "Traditional strong milk tea with cardamom.",
    category: "beverages",
    price: 100,
    ingredients: ["black tea", "milk", "sugar", "cardamom", "ginger"],
    allergens: ["dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 120,
    nutrition: { protein: 3, carbs: 18, fat: 4, fiber: 0, sugar: 16, sodium: 30 },
    healthTags: ["vegetarian", "traditional"],
    notRecommendedFor: ["diabetes", "lactose intolerance"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=600",
    isPopular: true,
    rating: 4.8,
    preparationTime: 8,
    availableFor: ["both"],
  },
  {
    name: "Cold Coffee",
    description: "Chilled coffee blended with milk and ice cream.",
    category: "beverages",
    price: 250,
    ingredients: ["coffee", "milk", "sugar", "ice cream", "ice"],
    allergens: ["dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 320,
    nutrition: { protein: 6, carbs: 48, fat: 12, fiber: 0, sugar: 42, sodium: 80 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["diabetes", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600",
    isPopular: true,
    rating: 4.6,
    preparationTime: 5,
    availableFor: ["both"],
  },
  {
    name: "Lemonade",
    description: "Homemade fresh lemonade with mint leaves.",
    category: "beverages",
    price: 160,
    ingredients: ["lemon", "sugar", "water", "mint", "ice"],
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 110,
    nutrition: { protein: 0, carbs: 28, fat: 0, fiber: 0, sugar: 26, sodium: 10 },
    healthTags: ["vegetarian", "vegan", "low-calorie"],
    notRecommendedFor: ["diabetes"],
    recommendedFor: ["weight loss"],
    image: "https://images.unsplash.com/photo-1513552885571-5e94e2816cf3?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 3,
    availableFor: ["both"],
  },
  {
    name: "Orange Juice",
    description: "Freshly squeezed orange juice. No added sugar.",
    category: "beverages",
    price: 200,
    ingredients: ["orange"],
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 110,
    nutrition: { protein: 2, carbs: 26, fat: 0, fiber: 2, sugar: 22, sodium: 5 },
    healthTags: ["vegetarian", "vegan", "low-calorie"],
    notRecommendedFor: ["diabetes"],
    recommendedFor: ["weight loss", "heart health"],
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 3,
    availableFor: ["both"],
  },
  {
    name: "Strawberry Shake",
    description: "Creamy milkshake with fresh strawberries.",
    category: "beverages",
    price: 280,
    ingredients: ["strawberries", "milk", "sugar", "ice cream"],
    allergens: ["dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 360,
    nutrition: { protein: 8, carbs: 52, fat: 14, fiber: 2, sugar: 48, sodium: 100 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["diabetes", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=600",
    isPopular: false,
    rating: 4.6,
    preparationTime: 5,
    availableFor: ["both"],
  },
  {
    name: "Watermelon Juice",
    description: "Fresh watermelon juice with a hint of mint.",
    category: "beverages",
    price: 180,
    ingredients: ["watermelon", "mint", "lime", "ice"],
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 70,
    nutrition: { protein: 1, carbs: 18, fat: 0, fiber: 1, sugar: 16, sodium: 5 },
    healthTags: ["vegetarian", "vegan", "low-calorie", "hydrating"],
    notRecommendedFor: ["diabetes"],
    recommendedFor: ["weight loss", "hydration"],
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600",
    isPopular: false,
    rating: 4.4,
    preparationTime: 3,
    availableFor: ["both"],
  },
  // ============================================
  // SEAFOOD (10 items)
  // ============================================
  {
    name: "Grilled Prawns",
    description: "Jumbo prawns marinated in garlic and herbs, grilled to perfection.",
    category: "seafood",
    price: 890,
    ingredients: ["prawns", "garlic", "lemon", "olive oil", "parsley", "black pepper"],
    allergens: ["shellfish"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 220,
    nutrition: { protein: 28, carbs: 4, fat: 10, fiber: 0, sugar: 1, sodium: 320 },
    healthTags: ["high-protein", "low-carb", "omega-3"],
    notRecommendedFor: ["shellfish allergy"],
    recommendedFor: ["weight loss", "muscle building", "heart health"],
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Fish Curry",
    description: "Fresh fish cooked in traditional spicy coconut curry.",
    category: "seafood",
    price: 750,
    ingredients: ["fish fillet", "coconut milk", "onion", "tomato", "ginger", "garlic", "spices"],
    allergens: ["fish"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 340,
    nutrition: { protein: 32, carbs: 12, fat: 18, fiber: 2, sugar: 4, sodium: 480 },
    healthTags: ["high-protein", "traditional"],
    notRecommendedFor: ["fish allergy", "kidney disease"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600",
    isPopular: true,
    rating: 4.8,
    preparationTime: 35,
    availableFor: ["both"],
  },
  {
    name: "Fried Calamari",
    description: "Crispy fried squid rings served with garlic aioli.",
    category: "seafood",
    price: 620,
    ingredients: ["squid", "flour", "paprika", "lemon", "garlic aioli"],
    allergens: ["shellfish", "gluten"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 380,
    nutrition: { protein: 22, carbs: 32, fat: 18, fiber: 1, sugar: 2, sodium: 520 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["shellfish allergy", "celiac disease"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Butter Garlic Prawns",
    description: "Prawns sautéed in butter garlic sauce with white wine.",
    category: "seafood",
    price: 950,
    ingredients: ["prawns", "butter", "garlic", "white wine", "lemon", "parsley"],
    allergens: ["shellfish", "dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 310,
    nutrition: { protein: 30, carbs: 5, fat: 18, fiber: 0, sugar: 2, sodium: 420 },
    healthTags: ["high-protein", "low-carb"],
    notRecommendedFor: ["shellfish allergy", "lactose intolerance"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=600",
    isPopular: true,
    rating: 4.8,
    preparationTime: 18,
    availableFor: ["both"],
  },
  {
    name: "Fish Tikka",
    description: "Boneless fish marinated in spices and grilled in tandoor.",
    category: "seafood",
    price: 680,
    ingredients: ["fish fillet", "yogurt", "ginger", "garlic", "red chili", "lemon", "spices"],
    allergens: ["fish", "dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 260,
    nutrition: { protein: 34, carbs: 4, fat: 12, fiber: 1, sugar: 2, sodium: 380 },
    healthTags: ["high-protein", "low-carb", "grilled"],
    notRecommendedFor: ["fish allergy", "lactose intolerance"],
    recommendedFor: ["weight loss", "muscle building"],
    image: "https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=600",
    isPopular: false,
    rating: 4.6,
    preparationTime: 25,
    availableFor: ["both"],
  },
  {
    name: "Prawn Curry",
    description: "Succulent prawns in rich, spicy coconut gravy.",
    category: "seafood",
    price: 820,
    ingredients: ["prawns", "coconut milk", "onion", "tomato", "tamarind", "spices"],
    allergens: ["shellfish"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: true,
    isDairyFree: true,
    calories: 310,
    nutrition: { protein: 28, carbs: 14, fat: 16, fiber: 2, sugar: 5, sodium: 520 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["shellfish allergy"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 30,
    availableFor: ["both"],
  },
  {
    name: "Grilled Salmon",
    description: "Atlantic salmon with lemon butter sauce and seasonal vegetables.",
    category: "seafood",
    price: 1450,
    ingredients: ["salmon", "lemon", "butter", "garlic", "asparagus", "broccoli"],
    allergens: ["fish", "dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 450,
    nutrition: { protein: 42, carbs: 8, fat: 26, fiber: 3, sugar: 3, sodium: 380 },
    healthTags: ["high-protein", "omega-3", "heart-healthy", "low-carb"],
    notRecommendedFor: ["fish allergy", "lactose intolerance"],
    recommendedFor: ["heart health", "weight loss", "muscle building", "diabetes"],
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600",
    isPopular: true,
    rating: 4.9,
    preparationTime: 25,
    availableFor: ["both"],
  },
  {
    name: "Classic Fish & Chips",
    description: "Beer-battered fish fillet served with crispy fries and tartar sauce.",
    category: "seafood",
    price: 720,
    ingredients: ["fish fillet", "beer batter", "potato", "tartar sauce", "lemon"],
    allergens: ["fish", "gluten", "eggs"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 680,
    nutrition: { protein: 32, carbs: 58, fat: 34, fiber: 3, sugar: 4, sodium: 680 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["fish allergy", "celiac disease", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1584724975670-6c31ce32771a?w=600",
    isPopular: true,
    rating: 4.6,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Lobster Thermidor",
    description: "Lobster meat in creamy white wine sauce, baked with cheese.",
    category: "seafood",
    price: 2200,
    ingredients: ["lobster", "white wine", "cream", "mustard", "cheese", "shallots"],
    allergens: ["shellfish", "dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 520,
    nutrition: { protein: 38, carbs: 12, fat: 34, fiber: 0, sugar: 6, sodium: 680 },
    healthTags: ["high-protein", "luxury"],
    notRecommendedFor: ["shellfish allergy", "lactose intolerance", "obesity"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=600",
    isPopular: false,
    rating: 4.8,
    preparationTime: 40,
    availableFor: ["both"],
  },
  {
    name: "Chilli Prawns",
    description: "Stir-fried prawns with bell peppers, onions in spicy chilli sauce.",
    category: "seafood",
    price: 780,
    ingredients: ["prawns", "bell pepper", "onion", "chilli sauce", "soy sauce", "ginger", "garlic"],
    allergens: ["shellfish", "gluten", "soy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: true,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 290,
    nutrition: { protein: 28, carbs: 18, fat: 12, fiber: 2, sugar: 6, sodium: 780 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["shellfish allergy", "hypertension"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 18,
    availableFor: ["both"],
  },
    // ============================================
  // CONTINENTAL (10 items)
  // ============================================
  {
    name: "Chicken Steak",
    description: "Grilled chicken breast served with mashed potatoes and grilled vegetables.",
    category: "continental",
    price: 850,
    ingredients: ["chicken breast", "mashed potatoes", "broccoli", "carrot", "peppercorn sauce"],
    allergens: ["dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 480,
    nutrition: { protein: 42, carbs: 32, fat: 20, fiber: 4, sugar: 6, sodium: 520 },
    healthTags: ["high-protein", "grilled"],
    notRecommendedFor: ["lactose intolerance"],
    recommendedFor: ["muscle building", "weight loss"],
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 25,
    availableFor: ["both"],
  },
  {
    name: "Beef Steak",
    description: "Tender beef sirloin cooked to your liking with red wine jus.",
    category: "continental",
    price: 1250,
    ingredients: ["beef sirloin", "butter", "rosemary", "thyme", "red wine jus"],
    allergens: ["dairy"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: true,
    isDairyFree: false,
    calories: 580,
    nutrition: { protein: 48, carbs: 4, fat: 38, fiber: 0, sugar: 2, sodium: 480 },
    healthTags: ["high-protein", "low-carb"],
    notRecommendedFor: ["heart disease", "obesity", "lactose intolerance"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600",
    isPopular: true,
    rating: 4.9,
    preparationTime: 30,
    availableFor: ["both"],
  },
  {
    name: "Chicken Alfredo Pasta",
    description: "Fettuccine in creamy parmesan sauce with grilled chicken.",
    category: "continental",
    price: 780,
    ingredients: ["fettuccine", "chicken breast", "cream", "parmesan", "garlic", "butter"],
    allergens: ["gluten", "dairy", "eggs"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 680,
    nutrition: { protein: 38, carbs: 58, fat: 32, fiber: 2, sugar: 4, sodium: 580 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["celiac disease", "lactose intolerance", "obesity"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1645112411344-4c6fd54baa34?w=600",
    isPopular: true,
    rating: 4.7,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Grilled Chicken Caesar Salad",
    description: "Romaine lettuce with grilled chicken, parmesan, croutons and Caesar dressing.",
    category: "continental",
    price: 650,
    ingredients: ["chicken breast", "romaine lettuce", "parmesan", "croutons", "caesar dressing"],
    allergens: ["gluten", "dairy", "eggs", "fish"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 380,
    nutrition: { protein: 35, carbs: 18, fat: 22, fiber: 4, sugar: 4, sodium: 680 },
    healthTags: ["high-protein", "low-carb"],
    notRecommendedFor: ["celiac disease"],
    recommendedFor: ["weight loss", "diabetes", "heart health"],
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=600",
    isPopular: false,
    rating: 4.5,
    preparationTime: 15,
    availableFor: ["both"],
  },
  {
    name: "Spaghetti Bolognese",
    description: "Classic Italian pasta with rich meat sauce.",
    category: "continental",
    price: 680,
    ingredients: ["spaghetti", "beef mince", "tomato", "onion", "carrot", "celery", "red wine"],
    allergens: ["gluten", "dairy", "eggs"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 590,
    nutrition: { protein: 32, carbs: 68, fat: 22, fiber: 4, sugar: 8, sodium: 620 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["celiac disease", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1599032901754-6b8e3a52dfd6?w=600",
    isPopular: true,
    rating: 4.6,
    preparationTime: 25,
    availableFor: ["both"],
  },
  {
    name: "Chicken Parmesan",
    description: "Breaded chicken topped with marinara sauce and melted cheese.",
    category: "continental",
    price: 890,
    ingredients: ["chicken breast", "breadcrumbs", "marinara sauce", "mozzarella", "parmesan"],
    allergens: ["gluten", "dairy", "eggs"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 620,
    nutrition: { protein: 48, carbs: 42, fat: 30, fiber: 3, sugar: 8, sodium: 880 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["celiac disease", "lactose intolerance", "obesity"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=600",
    isPopular: false,
    rating: 4.6,
    preparationTime: 25,
    availableFor: ["both"],
  },
  {
    name: "Fish and Chips",
    description: "Beer-battered fish with crispy fries, tartar sauce and lemon.",
    category: "continental",
    price: 720,
    ingredients: ["fish fillet", "beer batter", "potato", "tartar sauce", "lemon", "pea puree"],
    allergens: ["fish", "gluten", "eggs"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: true,
    calories: 680,
    nutrition: { protein: 32, carbs: 58, fat: 34, fiber: 4, sugar: 4, sodium: 720 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["fish allergy", "celiac disease", "obesity"],
    recommendedFor: [],
    image: "https://images.unsplash.com/photo-1584724975670-6c31ce32771a?w=600",
    isPopular: true,
    rating: 4.5,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce, fresh mozzarella and basil.",
    category: "continental",
    price: 750,
    ingredients: ["pizza dough", "tomato sauce", "mozzarella", "basil", "olive oil"],
    allergens: ["gluten", "dairy"],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 580,
    nutrition: { protein: 22, carbs: 72, fat: 24, fiber: 4, sugar: 6, sodium: 780 },
    healthTags: ["vegetarian"],
    notRecommendedFor: ["celiac disease", "lactose intolerance", "obesity"],
    recommendedFor: ["vegetarian"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600",
    isPopular: true,
    rating: 4.8,
    preparationTime: 20,
    availableFor: ["both"],
  },
  {
    name: "Lasagna",
    description: "Layered pasta with meat sauce, ricotta, mozzarella and parmesan.",
    category: "continental",
    price: 850,
    ingredients: ["lasagna sheets", "beef mince", "ricotta", "mozzarella", "parmesan", "tomato sauce"],
    allergens: ["gluten", "dairy", "eggs"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 720,
    nutrition: { protein: 38, carbs: 62, fat: 36, fiber: 4, sugar: 10, sodium: 880 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["celiac disease", "lactose intolerance", "obesity"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1574894709920-11b28e7367c3?w=600",
    isPopular: false,
    rating: 4.7,
    preparationTime: 35,
    availableFor: ["both"],
  },
  {
    name: "Chicken Cordon Bleu",
    description: "Chicken breast stuffed with ham and cheese, breaded and baked.",
    category: "continental",
    price: 980,
    ingredients: ["chicken breast", "ham", "swiss cheese", "breadcrumbs", "butter"],
    allergens: ["gluten", "dairy", "eggs"],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    isGlutenFree: false,
    isDairyFree: false,
    calories: 580,
    nutrition: { protein: 52, carbs: 28, fat: 32, fiber: 1, sugar: 4, sodium: 880 },
    healthTags: ["high-protein"],
    notRecommendedFor: ["celiac disease", "lactose intolerance", "obesity"],
    recommendedFor: ["muscle building"],
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600",
    isPopular: false,
    rating: 4.6,
    preparationTime: 30,
    availableFor: ["both"],
  },
];

// ──────────────────────────────────────────────
// ✅ SEED FUNCTION (YEH DEFINED HONA CHAHIYE)
// ──────────────────────────────────────────────
const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB connected");

    // DELETE ALL EXISTING ITEMS
    await MenuItem.deleteMany({});
    console.log("🗑️ Old menu cleared");

    // INSERT NEW ITEMS
    await MenuItem.insertMany(menuData);
    console.log(`🍽️ ${menuData.length} menu items seeded successfully!`);

    // Show summary
    const categories = [...new Set(menuData.map(i => i.category))];
    categories.forEach(cat => {
      const count = menuData.filter(i => i.category === cat).length;
      console.log(`   ${cat}: ${count} items`);
    });

  } catch (err) {
    console.error("❌ Seeding failed:", err);
  } finally {
    await mongoose.disconnect();
    console.log("🔌 Disconnected");
    process.exit();
  }
};

// ──────────────────────────────────────────────
// ✅ CALL THE FUNCTION
// ──────────────────────────────────────────────
seedDB();